version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    networks:
      - todo-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  todo-app:
    build: .
    ports:
      - "8080:8080"
      - "4848:4848"
    networks:
      - todo-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
networks:
  todo-network: